name: React Doctor

on:
  pull_request:
  push:
    branches: ["master"] # 1. Đổi từ main thành master để kích hoạt khi bạn push code

permissions:
  contents: read
  pull-requests: write

jobs:
  react-doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: millionco/react-doctor@main
        with:
          diff: master # 2. Đổi từ main thành master để công cụ biết đối chiếu thay đổi với nhánh nào
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on: "none"
