name: React Doctor Scan

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main", "master"]
jobs:
  diagnose:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # BẮT BUỘC có quyền write để Action có thể tự động comment lỗi vào PR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # BẮT BUỘC phải là 0 nếu bạn muốn dùng chế độ 'diff' (chỉ quét file bị thay đổi)

      - name: React Doctor
        uses: millionco/react-doctor@0.0.38
        with:
          # Token giúp bot bình luận kết quả trực tiếp lên Pull Request
          github-token: ${{ secrets.GITHUB_TOKEN }}

          # Tùy chọn quét thư mục cụ thể nếu repo của bạn là monorepo (ví dụ: 'apps/web')
          # directory: '.'
          # Báo lỗi và đánh fail CI nếu phát hiện lỗi (error, warning, hoặc none)
          fail-on: "error"
